import { useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from "@/components/ui/dialog";
import { FileText, HandCoins, ClipboardList, ImageIcon } from "lucide-react";
import { format } from "date-fns";

interface GmInvoiceDetail {
    gm: {
        id: string;
        gmType: string;
        companyName: string;
        salesPersonName: string | null;
        packageType: string;
        status: string;
        amountUsd: string;
        customerDollar: string | null;
        createdAt: string | null;
        drmId: string | null;
        memberId: string | null;
        orderId: string | null;
        entryType: string | null;
        packagePriceUsd: string | null;
        alibabaDiscountUsd: string | null;
        extraDiscountUsd: string | null;
        extraDiscountPkr: string | null;
        dollarRate: string | null;
        amountPkr: string | null;
        paymentStatus: string | null;
        notes: string | null;
        dropout: string | null;
        extension: string | null;
        installments: string | null;
        paymentProofUrl: string | null;
        addedByName: string | null;
    };
    invoices: Array<{
        id: string;
        invoiceType: string | null;
        status: string;
        amount: string;
        currency: string;
        autoGenerated: boolean;
        hodApprovedBy: string | null;
        hodApprovedAt: string | null;
        accountsApprovedBy: string | null;
        accountsApprovedAt: string | null;
        rejectedBy: string | null;
        rejectedAt: string | null;
        rejectionReason: string | null;
        paidAmount: string | null;
        paidDate: string | null;
        paymentMethod: string | null;
        receiptReference: string | null;
        projectName: string | null;
        createdAt: string | null;
        projects: Array<{ id: string; name: string; status: string; departmentType: string | null }>;
    }>;
    partialReceipts: Array<{
        id: string;
        amountUsd: string;
        amountPkr: string | null;
        receiptDate: string | null;
        method: string | null;
        reference: string | null;
    }>;
    loanTerms: {
        loanAmountUsd: string | null;
        companyCopayUsd: string | null;
        agreedReturnDate: string | null;
        adminApprovalStatus: string | null;
        adminApprovedAt: string | null;
        returnStatus: string | null;
        returnedAt: string | null;
        overdue: boolean;
    } | null;
    summary: {
        invoiceCount: number;
        paymentConfirmationStatus: string;
        partialReceivedTotal: string | null;
        partialPendingTotal: string | null;
    };
}

function money(value: string | number | null | undefined): string {
    const n = Number(value ?? 0);
    if (Number.isNaN(n)) return "$0";
    return `$${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

function fmtDate(value: string | null | undefined): string {
    if (!value) return "—";
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? "—" : format(d, "dd MMM yyyy");
}

function pkr(value: string | number | null | undefined): string {
    const n = Number(value ?? 0);
    if (Number.isNaN(n) || n === 0) return "—";
    return `₨${n.toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}

function DetailField({ label, value }: { label: string; value: React.ReactNode }) {
    return (
        <div>
            <span className="text-muted-foreground">{label}</span>
            <div className="font-semibold">{value ?? "—"}</div>
        </div>
    );
}

export function GmDetailInvoicesModal({
    gmId,
    onClose,
}: {
    gmId: string | null;
    onClose: () => void;
}) {
    const detailQuery = useQuery<GmInvoiceDetail>({
        queryKey: ["accounts-gm-invoice-detail", gmId],
        enabled: !!gmId,
        queryFn: async () => {
            const res = await apiRequest("GET", `/api/account/gm-entries/${gmId}/invoices`);
            if (!res.ok) throw new Error("Failed to load GM invoices");
            const body = await res.json();
            return body.data as GmInvoiceDetail;
        },
    });

    return (
        <Dialog open={!!gmId} onOpenChange={(open) => !open && onClose()}>
            <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-emerald-600" />
                        GM Detail &amp; Linked Invoices
                    </DialogTitle>
                    <DialogDescription>
                        {detailQuery.data?.gm
                            ? `${detailQuery.data.gm.companyName} · ${detailQuery.data.gm.gmType} · ${detailQuery.data.gm.status}`
                            : "Loading GM details…"}
                    </DialogDescription>
                </DialogHeader>

                {detailQuery.isLoading && <div className="py-8 text-center text-muted-foreground">Loading…</div>}
                {detailQuery.isError && <div className="py-8 text-center text-rose-600">Failed to load GM details.</div>}

                {detailQuery.data && (
                    <div className="space-y-5">
                        {/* Header facts */}
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                            <div><span className="text-muted-foreground">Amount</span><div className="font-semibold">{money(detailQuery.data.gm.amountUsd)}</div></div>
                            <div><span className="text-muted-foreground">Customer $</span><div className="font-semibold">{detailQuery.data.gm.customerDollar ? money(detailQuery.data.gm.customerDollar) : "—"}</div></div>
                            <div><span className="text-muted-foreground">Sales</span><div className="font-semibold">{detailQuery.data.gm.salesPersonName || "—"}</div></div>
                            <div><span className="text-muted-foreground">Created</span><div className="font-semibold">{fmtDate(detailQuery.data.gm.createdAt)}</div></div>
                        </div>

                        {/* Loan terms */}
                        {detailQuery.data.loanTerms && (
                            <div className="rounded-lg border p-3 bg-violet-50/50 dark:bg-zinc-900">
                                <h4 className="font-bold text-sm mb-2 flex items-center gap-1">
                                    <HandCoins className="h-4 w-4 text-violet-600" /> Loan Terms
                                    {detailQuery.data.loanTerms.overdue && <Badge variant="outline" className="text-[10px] bg-rose-100 text-rose-700 border-rose-200">OVERDUE</Badge>}
                                </h4>
                                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                                    <div><span className="text-muted-foreground">Loan Amt</span><div className="font-semibold">{money(detailQuery.data.loanTerms.loanAmountUsd)}</div></div>
                                    <div><span className="text-muted-foreground">Return By</span><div className="font-semibold">{fmtDate(detailQuery.data.loanTerms.agreedReturnDate)}</div></div>
                                    <div><span className="text-muted-foreground">Admin</span><div className="font-semibold">{detailQuery.data.loanTerms.adminApprovalStatus || "—"}</div></div>
                                    <div><span className="text-muted-foreground">Return</span><div className="font-semibold">{detailQuery.data.loanTerms.returnStatus || "—"}</div></div>
                                </div>
                            </div>
                        )}

                        {/* Partial receipts */}
                        {detailQuery.data.partialReceipts.length > 0 && (
                            <div>
                                <h4 className="font-bold text-sm mb-2">
                                    Partial Receipts
                                    {detailQuery.data.summary.partialPendingTotal != null && (
                                        <span className="ml-2 text-xs font-normal text-amber-600">
                                            Received {money(detailQuery.data.summary.partialReceivedTotal)} · Pending {money(detailQuery.data.summary.partialPendingTotal)}
                                        </span>
                                    )}
                                </h4>
                                <div className="rounded-lg border overflow-hidden">
                                    <Table>
                                        <TableHeader className="bg-slate-100/50">
                                            <TableRow>
                                                <TableHead>Date</TableHead>
                                                <TableHead className="text-right">Amount</TableHead>
                                                <TableHead>Method</TableHead>
                                                <TableHead>Reference</TableHead>
                                            </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                            {detailQuery.data.partialReceipts.map((r) => (
                                                <TableRow key={r.id}>
                                                    <TableCell className="text-sm">{fmtDate(r.receiptDate)}</TableCell>
                                                    <TableCell className="text-right text-sm">{money(r.amountUsd)}</TableCell>
                                                    <TableCell className="text-sm">{r.method || "—"}</TableCell>
                                                    <TableCell className="text-sm">{r.reference || "—"}</TableCell>
                                                </TableRow>
                                            ))}
                                        </TableBody>
                                    </Table>
                                </div>
                            </div>
                        )}

                        {/* Invoices */}
                        <div>
                            <h4 className="font-bold text-sm mb-2">Linked Invoices ({detailQuery.data.summary.invoiceCount})</h4>
                            {detailQuery.data.invoices.length === 0 ? (
                                <div className="text-sm text-muted-foreground py-4 text-center border rounded-lg">No invoices linked to this GM.</div>
                            ) : (
                                <div className="rounded-lg border overflow-hidden">
                                    <Table>
                                        <TableHeader className="bg-slate-100/50">
                                            <TableRow>
                                                <TableHead>Type</TableHead>
                                                <TableHead className="text-right">Amount</TableHead>
                                                <TableHead>Status</TableHead>
                                                <TableHead>HOD</TableHead>
                                                <TableHead>Accounts</TableHead>
                                                <TableHead>Project</TableHead>
                                            </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                            {detailQuery.data.invoices.map((inv) => (
                                                <TableRow key={inv.id}>
                                                    <TableCell className="text-sm">
                                                        {inv.invoiceType || "—"}
                                                        <div className="text-[10px] text-muted-foreground">{inv.autoGenerated ? "auto" : "manual"}</div>
                                                    </TableCell>
                                                    <TableCell className="text-right text-sm">{money(inv.amount)}</TableCell>
                                                    <TableCell><Badge variant="outline" className="text-[10px]">{inv.status}</Badge></TableCell>
                                                    <TableCell className="text-[11px]">{inv.hodApprovedAt ? `✓ ${fmtDate(inv.hodApprovedAt)}` : "—"}</TableCell>
                                                    <TableCell className="text-[11px]">{inv.accountsApprovedAt ? `✓ ${fmtDate(inv.accountsApprovedAt)}` : "—"}</TableCell>
                                                    <TableCell className="text-[11px]">
                                                        {inv.projects.length > 0
                                                            ? inv.projects.map((p) => `${p.name} (${p.status})`).join(", ")
                                                            : inv.projectName || "—"}
                                                    </TableCell>
                                                </TableRow>
                                            ))}
                                        </TableBody>
                                    </Table>
                                </div>
                            )}
                        </div>

                        {/* GM Entry Details — the original Add GM form submission */}
                        <div className="rounded-lg border p-4 bg-slate-50/60 dark:bg-zinc-900">
                            <h4 className="font-bold text-sm mb-3 flex items-center gap-1.5">
                                <ClipboardList className="h-4 w-4 text-slate-500" /> GM Entry Details
                            </h4>

                            <div className="space-y-4">
                                <div>
                                    <h5 className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-2">Identifiers</h5>
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                                        <DetailField label="DRM ID" value={detailQuery.data.gm.drmId} />
                                        <DetailField label="Member ID" value={detailQuery.data.gm.memberId} />
                                        <DetailField label="Order ID" value={detailQuery.data.gm.orderId} />
                                        <DetailField label="Type" value={detailQuery.data.gm.entryType} />
                                    </div>
                                </div>

                                <div>
                                    <h5 className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-2">Package &amp; Pricing</h5>
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                                        <DetailField label="Package" value={detailQuery.data.gm.packageType || "—"} />
                                        <DetailField label="Package Price" value={money(detailQuery.data.gm.packagePriceUsd)} />
                                        <DetailField label="AB Discount" value={money(detailQuery.data.gm.alibabaDiscountUsd)} />
                                        <DetailField label="Dollar Rate" value={detailQuery.data.gm.dollarRate || "—"} />
                                        <DetailField label="Extra $ Discount" value={money(detailQuery.data.gm.extraDiscountUsd)} />
                                        <DetailField label="Extra PKR Discount" value={pkr(detailQuery.data.gm.extraDiscountPkr)} />
                                        <DetailField label="PKR Amount" value={pkr(detailQuery.data.gm.amountPkr)} />
                                        <DetailField label="Payment Status" value={detailQuery.data.gm.paymentStatus} />
                                    </div>
                                </div>

                                <div>
                                    <h5 className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-2">Other</h5>
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                                        <DetailField label="Added By" value={detailQuery.data.gm.addedByName} />
                                        <DetailField label="Dropout" value={detailQuery.data.gm.dropout} />
                                        <DetailField label="Extension" value={detailQuery.data.gm.extension} />
                                        <DetailField
                                            label="Payment Screenshot"
                                            value={
                                                detailQuery.data.gm.paymentProofUrl ? (
                                                    <a
                                                        href={detailQuery.data.gm.paymentProofUrl}
                                                        target="_blank"
                                                        rel="noopener noreferrer"
                                                        className="inline-flex items-center gap-1 text-emerald-600 hover:underline font-medium"
                                                    >
                                                        <ImageIcon className="h-3.5 w-3.5" /> View
                                                    </a>
                                                ) : (
                                                    "—"
                                                )
                                            }
                                        />
                                    </div>
                                </div>

                                {detailQuery.data.gm.notes && (
                                    <div>
                                        <h5 className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground mb-2">Notes</h5>
                                        <p className="text-sm bg-white dark:bg-zinc-950 border rounded-md p-2.5 whitespace-pre-wrap">
                                            {detailQuery.data.gm.notes}
                                        </p>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                )}
            </DialogContent>
        </Dialog>
    );
}
