import { Router } from "express";
import { pool } from "../db";
import { NotificationService } from "./services/notification-service";
import { projectsRepository } from "../repositories/projects.repository";

const router = Router();

// Helper to get userId from req (if not present, fallback for safe typing)
function getUserId(req: any): string {
    return req.user?.userId || req.user?.id || "";
}

// GET /api/product-posting-invoices - List product posting invoices
router.get("/", async (req: any, res: any) => {
    try {
        const userId = getUserId(req);
        const role = String(req.user?.activeRoleId || req.user?.roleId || "").toLowerCase();
        
        let query = `SELECT p.id, p.customer_id, p.invoice_number as "invoiceNumber",
                    p.invoice_type as "invoiceType", p.project_name as "projectName",
                    p.company_name as "companyName", p.sales_exec_id as "salesExecId",
                    COALESCE(u.name, u.username) as "personName", p.amount,
                    p.status, p.created_at as "createdAt",
                    p.auto_generated as "autoGenerated", p.payment_method as "paymentMethod",
                    p.gm_id as "gmId", gm.approval_status as "gmApprovalStatus"
             FROM drm.product_posting_invoices p
             LEFT JOIN drm.users u ON u.id = p.sales_exec_id
             LEFT JOIN drm.gm_entries gm ON gm.id::text = p.gm_id`;
             
        let params = [];
        if (role === 'sales_executive') {
            query += ` WHERE p.sales_exec_id = $1`;
            params.push(userId);
        }
        
        query += ` ORDER BY p.created_at DESC`;

        const { rows } = await pool.query(query, params);
        return res.json({ success: true, data: rows });
    } catch (error) {
        console.error("Error fetching product posting invoices:", error);
        return res.status(500).json({ error: "Failed to fetch invoices" });
    }
});

// POST /api/product-posting-invoices - Create new manual product posting invoice
router.post("/", async (req: any, res: any) => {
    try {
        const { companyName, invoiceType, customerId, amount, paymentMethod } = req.body;
        const userId = getUserId(req);
        const { rows } = await pool.query(
            `INSERT INTO drm.product_posting_invoices (
                invoice_number, amount, sales_exec_id, customer_id, project_name,
                company_name, status, invoice_type, auto_generated, payment_method, generated_by, generated_at
             ) VALUES (
                'INV-' || nextval('drm.product_posting_invoice_number_seq'),
                $1, $2, $3, $4, $5, 'PENDING_HOD', $4, false, $6, $2, now()
             ) RETURNING *`,
            [amount || 0, userId, customerId || null, invoiceType || 'Product Posting', companyName || '', paymentMethod || null]
        );
        return res.json(rows[0]);
    } catch (error) {
        console.error("Error creating product posting invoice:", error);
        return res.status(500).json({ error: "Failed to create invoice" });
    }
});

// PATCH /api/product-posting-invoices/:id - Update invoice details (e.g. from Action Modal)
router.patch("/:id", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        const { amount, paymentMethod } = req.body;
        
        let updates = [];
        let params = [];
        let paramIdx = 1;
        
        if (amount !== undefined) {
            updates.push(`amount = $${paramIdx++}`);
            params.push(amount);
        }
        if (paymentMethod !== undefined) {
            updates.push(`payment_method = $${paramIdx++}`);
            params.push(paymentMethod);
        }
        
        if (updates.length === 0) return res.json({ success: true });
        
        params.push(id);
        const { rows } = await pool.query(
            `UPDATE drm.product_posting_invoices SET ${updates.join(', ')} WHERE id = $${paramIdx} RETURNING *`,
            params
        );
        return res.json({ success: true, data: rows[0] });
    } catch (error) {
        console.error("Error updating invoice:", error);
        return res.status(500).json({ error: "Failed to update invoice" });
    }
});

// POST /api/product-posting-invoices/:id/hod-approve - Approve by HOD
router.post("/:id/hod-approve", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        const userId = getUserId(req);

        // HOD approval requires the invoice to be free (amount = 0)
        const checkRes = await pool.query(`SELECT amount, sales_exec_id, company_name FROM drm.product_posting_invoices WHERE id = $1`, [id]);
        if (!checkRes.rows.length) return res.status(404).json({ error: "Invoice not found" });

        if (Number(checkRes.rows[0].amount) > 0) {
            return res.status(400).json({ error: "Invoice must be marked as Free before HOD can approve." });
        }

        const { rows } = await pool.query(
            `UPDATE drm.product_posting_invoices
             SET status = 'PENDING_ACCOUNT', hod_approved_by = $2, hod_approved_at = NOW()
             WHERE id = $1 RETURNING *`,
            [id, userId || null]
        );
        
        return res.json({ success: true, data: rows[0] });
    } catch (error) {
        console.error("Error in hod-approve:", error);
        return res.status(500).json({ error: "Failed to approve" });
    }
});

// POST /api/product-posting-invoices/:id/hod-reject - Reject by HOD
router.post("/:id/hod-reject", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        const { reason } = req.body;
        const userId = getUserId(req);
        const { rows } = await pool.query(
            `UPDATE drm.product_posting_invoices
             SET status = 'REJECTED_HOD', rejected_by = $2, rejected_at = NOW(), rejection_reason = $3
             WHERE id = $1 RETURNING *`,
            [id, userId || null, reason || null]
        );
        
        // Notify sales executive
        if (rows[0] && rows[0].sales_exec_id) {
            await NotificationService.notify({
                userId: rows[0].sales_exec_id,
                message: `Your product posting invoice for ${rows[0].company_name} was rejected by HOD. Reason: ${reason || 'N/A'}`,
                type: "ERROR",
                targetUrl: "/product-posting/invoices"
            }).catch((e: any) => console.error("Notification failed", e));
        }
        
        return res.json({ success: true, data: rows[0] });
    } catch (error) {
        console.error("Error in hod-reject:", error);
        return res.status(500).json({ error: "Failed to reject" });
    }
});

// POST /api/product-posting-invoices/:id/account-approve - Approve by Account Manager
router.post("/:id/account-approve", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        const userId = getUserId(req);

        const gateRes = await pool.query(
            `SELECT p.gm_id AS "gmId", gm.approval_status AS "gmApprovalStatus"
             FROM drm.product_posting_invoices p
             LEFT JOIN drm.gm_entries gm ON gm.id::text = p.gm_id
             WHERE p.id = $1`,
            [id]
        );
        if (!gateRes.rows.length) return res.status(404).json({ error: "Invoice not found" });
        const { gmId, gmApprovalStatus } = gateRes.rows[0];
        if (gmId && gmApprovalStatus !== 'approved') {
            return res.status(400).json({
                error: "This invoice's GM entry has not been approved by the Account Manager yet. Approve the GM itself before approving this invoice."
            });
        }

        const { rows } = await pool.query(
            `UPDATE drm.product_posting_invoices
             SET status = 'APPROVED', accounts_approved_by = $2, accounts_approved_at = NOW()
             WHERE id = $1 RETURNING *`,
            [id, userId || null]
        );

        // Generate project for the invoice automatically on Account Approval
        if (rows[0]) {
            const invoice = rows[0];
            try {
                // Determine department type based on invoice type
                let deptType = 'PRODUCT_POSTING';
                if (invoice.invoice_type && String(invoice.invoice_type).toLowerCase().includes('minisite')) {
                    deptType = 'DND';
                }
                
                await pool.query(
                    `INSERT INTO drm.projects (
                        invoice_id, name, customer_id, owner_user_id, status, department_type, invoice_type, created_at, updated_at
                    ) VALUES (
                        $1, $2, $3, $4, 'Active', $5, $6, now(), now()
                    )`,
                    [
                        invoice.id, 
                        invoice.project_name || invoice.invoice_type || 'Product Posting',
                        invoice.customer_id,
                        invoice.sales_exec_id,
                        deptType,
                        invoice.invoice_type
                    ]
                );
                
                // Notify sales executive
                if (invoice.sales_exec_id) {
                    await NotificationService.notify({
                        userId: invoice.sales_exec_id,
                        message: `Your product posting invoice for ${invoice.company_name} was approved by Accounts. Project has been generated!`,
                        type: "SUCCESS",
                        targetUrl: "/pms"
                    }).catch((e: any) => console.error("Notification failed", e));
                }
            } catch (err) {
                console.error("Failed to generate project during account approval:", err);
            }
        }
        
        return res.json({ success: true, data: rows[0] });
    } catch (error) {
        console.error("Error in account-approve:", error);
        return res.status(500).json({ error: "Failed to approve" });
    }
});

// POST /api/product-posting-invoices/:id/account-reject - Reject by Account Manager
router.post("/:id/account-reject", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        const { reason } = req.body;
        const userId = getUserId(req);
        const { rows } = await pool.query(
            `UPDATE drm.product_posting_invoices
             SET status = 'REJECTED_ACCOUNT', rejected_by = $2, rejected_at = NOW(), rejection_reason = $3
             WHERE id = $1 RETURNING *`,
            [id, userId || null, reason || null]
        );
        
        // Notify sales executive
        if (rows[0] && rows[0].sales_exec_id) {
            await NotificationService.notify({
                userId: rows[0].sales_exec_id,
                message: `Your product posting invoice for ${rows[0].company_name} was rejected by Accounts. Reason: ${reason || 'N/A'}`,
                type: "ERROR",
                targetUrl: "/product-posting/invoices"
            }).catch((e: any) => console.error("Notification failed", e));
        }
        
        return res.json({ success: true, data: rows[0] });
    } catch (error) {
        console.error("Error in account-reject:", error);
        return res.status(500).json({ error: "Failed to reject" });
    }
});

// POST /api/product-posting-invoices/:id/mark-free - Mark an invoice as Free
router.post("/:id/mark-free", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        const { rows } = await pool.query(
            `UPDATE drm.product_posting_invoices SET amount = 0, payment_method = 'Free' WHERE id = $1 RETURNING *`,
            [id]
        );
        return res.json({ success: true, data: rows[0] });
    } catch (error) {
        console.error("Error in mark-free:", error);
        return res.status(500).json({ error: "Failed to mark as free" });
    }
});

// POST /api/product-posting-invoices/:id/generate-project - Idempotent project generation
router.post("/:id/generate-project", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        
        // Check if project already exists
        const projRes = await pool.query(`SELECT id FROM drm.projects WHERE invoice_id = $1`, [id]);
        if (projRes.rows.length > 0) {
            return res.json({ success: true, data: { status: 'Active', held: false, linked: true, created: false }});
        }
        
        const invRes = await pool.query(`SELECT * FROM drm.product_posting_invoices WHERE id = $1`, [id]);
        if (!invRes.rows.length) return res.status(404).json({ error: "Invoice not found" });
        const invoice = invRes.rows[0];
        
        let deptType = 'PRODUCT_POSTING';
        if (invoice.invoice_type && String(invoice.invoice_type).toLowerCase().includes('minisite')) {
            deptType = 'DND';
        }
        
        await pool.query(
            `INSERT INTO drm.projects (
                invoice_id, name, customer_id, owner_user_id, status, department_type, invoice_type, created_at, updated_at
            ) VALUES (
                $1, $2, $3, $4, 'Active', $5, $6, now(), now()
            )`,
            [
                invoice.id, 
                invoice.project_name || invoice.invoice_type || 'Product Posting',
                invoice.customer_id,
                invoice.sales_exec_id,
                deptType,
                invoice.invoice_type
            ]
        );
        
        return res.json({ success: true, data: { status: 'Active', held: false, linked: true, created: true }});
    } catch (error) {
        console.error("Error in generate-project:", error);
        return res.status(500).json({ error: "Failed to generate project" });
    }
});

// POST /api/product-posting-invoices/:id/resubmit - Resubmit to HOD
router.post("/:id/resubmit", async (req: any, res: any) => {
    try {
        const { id } = req.params;
        const { rows } = await pool.query(
            `UPDATE drm.product_posting_invoices SET status = 'PENDING_HOD' WHERE id = $1 RETURNING *`,
            [id]
        );
        return res.json({ success: true, data: rows[0] });
    } catch (error) {
        console.error("Error in resubmit:", error);
        return res.status(500).json({ error: "Failed to resubmit" });
    }
});

// GET /api/product-posting/manager/project-stats
router.get("/manager/project-stats", async (req: any, res: any) => {
    try {
        const { rows } = await pool.query(`
            SELECT
                COUNT(*)::integer as total,
                SUM(CASE WHEN p.status = 'Active' THEN 1 ELSE 0 END)::integer as pending,
                SUM(CASE WHEN p.status = 'Completed' THEN 1 ELSE 0 END)::integer as complete,
                SUM(CASE WHEN p.status = 'OnHold' THEN 1 ELSE 0 END)::integer as free
            FROM drm.projects p
            WHERE p.department_type IN ('PRODUCT_POSTING', 'DND')
        `);
        return res.json(rows[0] || { total: 0, pending: 0, complete: 0, free: 0 });
    } catch (error) {
        console.error("Error fetching project stats:", error);
        return res.status(500).json({ error: "Failed to fetch stats" });
    }
});

// GET /api/product-posting/manager/daily-submissions
router.get("/manager/daily-submissions", async (req: any, res: any) => {
    try {
        const { rows } = await pool.query(`
            SELECT 
                u.name, 
                COUNT(*)::integer as submitted_count, 
                MAX(w.executive_submitted_at) as last_submitted_at,
                (
                    SELECT p.name 
                    FROM drm.projects p 
                    JOIN drm.product_posting_workflows w2 ON w2.project_id = p.id
                    WHERE w2.executive_user_id = w.executive_user_id 
                    ORDER BY w2.executive_submitted_at DESC LIMIT 1
                ) as last_task_title
            FROM drm.product_posting_workflows w
            JOIN drm.users u ON u.id = w.executive_user_id
            WHERE w.executive_submitted_at >= CURRENT_DATE
            GROUP BY u.name, w.executive_user_id
        `);
        return res.json({ success: true, data: rows });
    } catch (error) {
        console.error("Error fetching daily submissions:", error);
        return res.status(500).json({ error: "Failed to fetch daily submissions" });
    }
});

// GET /api/product-posting/manager/queue
router.get("/manager/queue", async (req: any, res: any) => {
    try {
        const { rows } = await pool.query(`
            SELECT 
                w.id as workflow_id, w.current_phase as "currentPhase", w.task_id as "taskId",
                w.executive_submitted_at as "executiveSubmittedAt", w.updated_at as "updatedAt",
                w.overtime_requested_minutes as "overtimeRequestedMinutes",
                w.overtime_approved_minutes as "overtimeApprovedMinutes",
                w.overtime_reason as "overtimeReason",
                p.id as project_id, p.name as project_name, COALESCE(c.company_name, i.company_name) as company_name, p.project_number as project_number,
                i.project_name as invoice_project_name,
                COALESCE((
                    SELECT json_agg(json_build_object('documentUrl', d.document_url)) 
                    FROM drm.project_documents d 
                    WHERE d.project_id = w.project_id
                ), '[]'::json) as documents
            FROM drm.product_posting_workflows w
            JOIN drm.projects p ON p.id = w.project_id
            LEFT JOIN drm.customers c ON c.id = p.customer_id
            LEFT JOIN drm.product_posting_invoices i ON i.id = p.invoice_id
            ORDER BY w.updated_at DESC
        `);

        // Format data to match frontend expectations
        const data = rows.map(row => ({
            workflowId: row.workflow_id,
            currentPhase: row.currentPhase || "PENDING_PROJECT",
            phaseLabel: row.currentPhase ? row.currentPhase.replace(/_/g, ' ') : "PENDING PROJECT",
            taskId: row.taskId,
            executiveSubmittedAt: row.executiveSubmittedAt,
            updatedAt: row.updatedAt,
            overtimeRequestedMinutes: row.overtimeRequestedMinutes || 0,
            overtimeApprovedMinutes: row.overtimeApprovedMinutes || 0,
            overtimeReason: row.overtimeReason,
            overtimeExceededBy: 0, // Calculate this properly if needed based on duration
            documents: row.documents || [],
            invoiceProjectName: row.invoice_project_name,
            project: {
                id: row.project_id,
                name: row.project_name,
                companyName: row.company_name,
                projectNumber: row.project_number
            }
        }));

        return res.json({ success: true, data });
    } catch (error) {
        console.error("Error fetching manager queue:", error);
        return res.status(500).json({ error: "Failed to fetch manager queue" });
    }
});

export const productPostingWorkflowRouter = router;
