export const recordGmSalesAudit = async (arg?: any) => {};
export const GM_SALES_AUDIT_ACTIONS = {
  GM_CREATE: "GM_CREATE",
  GM_TYPE_CHANGE_DENIED: "GM_TYPE_CHANGE_DENIED",
  GM_INVOICE_GENERATED: "GM_INVOICE_GENERATED",
  GM_UPDATE: "GM_UPDATE",
  GM_DELETE: "GM_DELETE",
  GM_THRESHOLD_VALIDATION_FAILED: "GM_THRESHOLD_VALIDATION_FAILED",
  GM_CREATE_UNAUTHORIZED_ATTEMPT: "GM_CREATE_UNAUTHORIZED_ATTEMPT",
  GM_TYPE_SET: "GM_TYPE_SET",
  GM_FIX_STATUS: "GM_FIX_STATUS",
  GM_PARTIAL_RECEIPT_ADD: "GM_PARTIAL_RECEIPT_ADD",
  GM_PARTIAL_FINAL_APPROVE: "GM_PARTIAL_FINAL_APPROVE",
  GM_LOAN_TERMS_ADD: "GM_LOAN_TERMS_ADD",
  GM_LOAN_ADMIN_APPROVE: "GM_LOAN_ADMIN_APPROVE",
  GM_LOAN_RETURN_UPDATE: "GM_LOAN_RETURN_UPDATE"
};
