export const recordGmSalesAudit = async () => {};
export const GM_SALES_AUDIT_ACTIONS = {
  GM_CREATE: "GM_CREATE",
  GM_TYPE_CHANGE_DENIED: "GM_TYPE_CHANGE_DENIED",
  GM_INVOICE_GENERATED: "GM_INVOICE_GENERATED",
  GM_UPDATE: "GM_UPDATE",
  GM_DELETE: "GM_DELETE"
};
