import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from "@/components/ui/dialog";
import {
    Wallet,
    Layers,
    HandCoins,
    AlertTriangle,
    Clock,
    Eye,
    Receipt,
    FileText,
} from "lucide-react";
import { format } from "date-fns";

/**
 * Accounts dashboard GM type + invoice view (Patch 5 Stage 7, Parts C/D).
 * Consumes GET /api/accounts/dashboard/gm-summary for Full/Partial/Loan totals,
 * partial received/pending, loan due-soon/overdue and a recent-GM table enriched
 * with linked invoice statuses + payment confirmation. Clicking a row opens the
 * GM detail dialog backed by GET /api/account/gm-entries/:id/invoices.
 */

interface GmSummaryTotals {
    totalGmCount: number;
    fullGmCount: number;
    partialGmCount: number;
    loanGmCount: number;
    totalGmAmount: string;
    fullGmAmount: string;
    partialGmTotalAmount: string;
    partialGmReceivedAmount: string;
    partialGmPendingAmount: string;
    loanGmAmount: string;
    loanDueSoonCount: number;
    loanOverdueCount: number;
}

interface RecentGm {
    id: string;
    gmType: "FULL" | "PARTIAL" | "LOAN";
    companyName: string;
    salesPersonName: string | null;
    packageType: string;
    status: string;
    createdAt: string | null;
    amountUsd: string;
    customerDollar: string | null;
    partialReceivedAmount: string | null;
    partialPendingAmount: string | null;
    loan: {
        loanAmountUsd: string | null;
        agreedReturnDate: string | null;
        returnStatus: string | null;
        adminApprovalStatus: string | null;
        overdue: boolean;
    } | null;
    invoiceStatuses: string[];
    invoiceCount: number;
    paymentConfirmationStatus: string;
}

interface GmSummaryResponse {
    totals: GmSummaryTotals;
    byStatus: { status: string; count: number; amount: string }[];
    recentGms: RecentGm[];
    dueSoonDays: number;
}

interface GmInvoiceDetail {
    gm: {
        id: string;
        gmType: string;
        companyName: string;
        salesPersonName: string | null;
        packageType: string;
        status: string;
        amountUsd: string;
        customerDollar: string | null;
        createdAt: string | null;
    };
    invoices: Array<{
        id: string;
        invoiceType: string | null;
        status: string;
        amount: string;
        currency: string;
        autoGenerated: boolean;
        hodApprovedBy: string | null;
        hodApprovedAt: string | null;
        accountsApprovedBy: string | null;
        accountsApprovedAt: string | null;
        rejectedBy: string | null;
        rejectedAt: string | null;
        rejectionReason: string | null;
        paidAmount: string | null;
        paidDate: string | null;
        paymentMethod: string | null;
        receiptReference: string | null;
        projectName: string | null;
        createdAt: string | null;
        projects: Array<{ id: string; name: string; status: string; departmentType: string | null }>;
    }>;
    partialReceipts: Array<{
        id: string;
        amountUsd: string;
        amountPkr: string | null;
        receiptDate: string | null;
        method: string | null;
        reference: string | null;
    }>;
    loanTerms: {
        loanAmountUsd: string | null;
        companyCopayUsd: string | null;
        agreedReturnDate: string | null;
        adminApprovalStatus: string | null;
        adminApprovedAt: string | null;
        returnStatus: string | null;
        returnedAt: string | null;
        overdue: boolean;
    } | null;
    summary: {
        invoiceCount: number;
        paymentConfirmationStatus: string;
        partialReceivedTotal: string | null;
        partialPendingTotal: string | null;
    };
}

const EMPTY_FILTERS = {
    gmType: "",
    status: "",
    dateFrom: "",
    dateTo: "",
    customer: "",
    invoiceStatus: "",
};

function money(value: string | number | null | undefined): string {
    const n = Number(value ?? 0);
    if (Number.isNaN(n)) return "$0";
    return `$${n.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

function fmtDate(value: string | null | undefined): string {
    if (!value) return "—";
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? "—" : format(d, "dd MMM yyyy");
}

function gmTypeBadge(type: string) {
    const map: Record<string, string> = {
        FULL: "bg-emerald-100 text-emerald-700 border-emerald-200",
        PARTIAL: "bg-amber-100 text-amber-700 border-amber-200",
        LOAN: "bg-violet-100 text-violet-700 border-violet-200",
    };
    return map[type] || "bg-slate-100 text-slate-700 border-slate-200";
}

function paymentBadge(status: string) {
    const map: Record<string, string> = {
        PAID: "bg-emerald-100 text-emerald-700 border-emerald-200",
        APPROVED: "bg-blue-100 text-blue-700 border-blue-200",
        PENDING: "bg-amber-100 text-amber-700 border-amber-200",
        OTHER: "bg-slate-100 text-slate-700 border-slate-200",
        NONE: "bg-slate-100 text-slate-500 border-slate-200",
    };
    return map[status] || "bg-slate-100 text-slate-600 border-slate-200";
}

const SummaryStat = ({
    title,
    value,
    sub,
    icon: Icon,
    color,
}: {
    title: string;
    value: React.ReactNode;
    sub?: React.ReactNode;
    icon: any;
    color: string;
}) => (
    <div className="rounded-xl border bg-white p-4 dark:bg-zinc-900">
        <div className="flex items-center justify-between pb-1">
            <p className="text-xs font-medium text-muted-foreground">{title}</p>
            <div className={`p-1.5 rounded-full ${color} bg-opacity-10`}>
                <Icon className={`h-3.5 w-3.5 ${color.replace("bg-", "text-")}`} />
            </div>
        </div>
        <div className="text-xl font-bold text-slate-900 dark:text-zinc-100">{value}</div>
        {sub && <p className="text-[11px] text-muted-foreground mt-0.5">{sub}</p>}
    </div>
);

export function AccountsGmSummaryWidget() {
    const [filters, setFilters] = useState({ ...EMPTY_FILTERS });
    const [appliedFilters, setAppliedFilters] = useState({ ...EMPTY_FILTERS });
    const [detailGmId, setDetailGmId] = useState<string | null>(null);

    const buildQs = (f: typeof EMPTY_FILTERS) => {
        const params = new URLSearchParams();
        if (f.gmType) params.set("gmType", f.gmType);
        if (f.status) params.set("status", f.status);
        if (f.dateFrom) params.set("dateFrom", new Date(f.dateFrom).toISOString());
        if (f.dateTo) params.set("dateTo", new Date(f.dateTo).toISOString());
        if (f.customer) params.set("customer", f.customer);
        if (f.invoiceStatus) params.set("invoiceStatus", f.invoiceStatus);
        params.set("recentLimit", "15");
        const qs = params.toString();
        return qs ? `?${qs}` : "";
    };

    const summaryQuery = useQuery<GmSummaryResponse>({
        queryKey: ["accounts-gm-summary", appliedFilters],
        queryFn: async () => {
            const res = await apiRequest("GET", `/api/accounts/dashboard/gm-summary${buildQs(appliedFilters)}`);
            if (!res.ok) throw new Error("Failed to load GM summary");
            const body = await res.json();
            return body.data as GmSummaryResponse;
        },
    });

    const detailQuery = useQuery<GmInvoiceDetail>({
        queryKey: ["accounts-gm-invoice-detail", detailGmId],
        enabled: !!detailGmId,
        queryFn: async () => {
            const res = await apiRequest("GET", `/api/account/gm-entries/${detailGmId}/invoices`);
            if (!res.ok) throw new Error("Failed to load GM invoices");
            const body = await res.json();
            return body.data as GmInvoiceDetail;
        },
    });

    const totals = summaryQuery.data?.totals;
    const recentGms = summaryQuery.data?.recentGms ?? [];
    const byStatus = summaryQuery.data?.byStatus ?? [];
    const dueSoonDays = summaryQuery.data?.dueSoonDays ?? 7;

    const applyFilters = () => setAppliedFilters({ ...filters });
    const clearFilters = () => {
        setFilters({ ...EMPTY_FILTERS });
        setAppliedFilters({ ...EMPTY_FILTERS });
    };

    const selectVal = (v: string) => v || "all";
    const fromSelect = (v: string) => (v === "all" ? "" : v);

    return (
        <Card className="border-none shadow-md bg-white dark:bg-zinc-900" data-testid="card-accounts-gm-summary">
            <CardHeader className="flex flex-row items-center justify-between py-4 px-6 border-b">
                <div>
                    <CardTitle className="text-xl font-bold text-slate-800 dark:text-zinc-100">
                        GM &amp; Invoice Overview
                    </CardTitle>
                    <p className="text-xs text-muted-foreground mt-1">
                        Full / Partial / Loan breakdown with linked invoice approvals
                    </p>
                </div>
            </CardHeader>
            <CardContent className="p-6 space-y-6">
                {/* Filters */}
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-7 gap-3 items-end">
                    <div className="space-y-1">
                        <Label className="text-xs">GM Type</Label>
                        <Select value={selectVal(filters.gmType)} onValueChange={(v) => setFilters((p) => ({ ...p, gmType: fromSelect(v) }))}>
                            <SelectTrigger data-testid="filter-gm-type"><SelectValue placeholder="All" /></SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">All</SelectItem>
                                <SelectItem value="FULL">Full</SelectItem>
                                <SelectItem value="PARTIAL">Partial</SelectItem>
                                <SelectItem value="LOAN">Loan</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                    <div className="space-y-1">
                        <Label className="text-xs">Status</Label>
                        <Select value={selectVal(filters.status)} onValueChange={(v) => setFilters((p) => ({ ...p, status: fromSelect(v) }))}>
                            <SelectTrigger data-testid="filter-gm-status"><SelectValue placeholder="All" /></SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">All</SelectItem>
                                <SelectItem value="Pending">Pending</SelectItem>
                                <SelectItem value="Approved">Approved</SelectItem>
                                <SelectItem value="Rejected">Rejected</SelectItem>
                                <SelectItem value="Completed">Completed</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                    <div className="space-y-1">
                        <Label className="text-xs">Invoice Status</Label>
                        <Select value={selectVal(filters.invoiceStatus)} onValueChange={(v) => setFilters((p) => ({ ...p, invoiceStatus: fromSelect(v) }))}>
                            <SelectTrigger data-testid="filter-invoice-status"><SelectValue placeholder="All" /></SelectTrigger>
                            <SelectContent>
                                <SelectItem value="all">All</SelectItem>
                                <SelectItem value="PENDING_HOD">Pending HOD</SelectItem>
                                <SelectItem value="PENDING_ACCOUNT">Pending Account</SelectItem>
                                <SelectItem value="APPROVED">Approved</SelectItem>
                                <SelectItem value="REJECTED">Rejected</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>
                    <div className="space-y-1">
                        <Label className="text-xs">Customer</Label>
                        <Input
                            data-testid="filter-customer"
                            placeholder="Company name"
                            value={filters.customer}
                            onChange={(e) => setFilters((p) => ({ ...p, customer: e.target.value }))}
                        />
                    </div>
                    <div className="space-y-1">
                        <Label className="text-xs">From</Label>
                        <Input type="date" data-testid="filter-date-from" value={filters.dateFrom} onChange={(e) => setFilters((p) => ({ ...p, dateFrom: e.target.value }))} />
                    </div>
                    <div className="space-y-1">
                        <Label className="text-xs">To</Label>
                        <Input type="date" data-testid="filter-date-to" value={filters.dateTo} onChange={(e) => setFilters((p) => ({ ...p, dateTo: e.target.value }))} />
                    </div>
                    <div className="flex gap-2">
                        <Button onClick={applyFilters} className="bg-emerald-600 hover:bg-emerald-700" data-testid="button-apply-filters">Apply</Button>
                        <Button variant="outline" onClick={clearFilters} data-testid="button-clear-filters">Clear</Button>
                    </div>
                </div>

                {/* Summary stats */}
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
                    <SummaryStat title="Full GMs" value={totals?.fullGmCount ?? 0} sub={money(totals?.fullGmAmount)} icon={Wallet} color="bg-emerald-500" />
                    <SummaryStat
                        title="Partial GMs"
                        value={totals?.partialGmCount ?? 0}
                        sub={`Rec ${money(totals?.partialGmReceivedAmount)} · Due ${money(totals?.partialGmPendingAmount)}`}
                        icon={Layers}
                        color="bg-amber-500"
                    />
                    <SummaryStat title="Loan GMs" value={totals?.loanGmCount ?? 0} sub={money(totals?.loanGmAmount)} icon={HandCoins} color="bg-violet-500" />
                    <SummaryStat title="Loan Overdue" value={totals?.loanOverdueCount ?? 0} sub="past return date" icon={AlertTriangle} color="bg-rose-500" />
                    <SummaryStat title={`Loan Due ≤${dueSoonDays}d`} value={totals?.loanDueSoonCount ?? 0} sub="returning soon" icon={Clock} color="bg-orange-500" />
                    <SummaryStat title="Total GMs" value={totals?.totalGmCount ?? 0} sub={money(totals?.totalGmAmount)} icon={Receipt} color="bg-blue-500" />
                </div>

                {/* By status chips */}
                {byStatus.length > 0 && (
                    <div className="flex flex-wrap gap-2">
                        {byStatus.map((s) => (
                            <Badge key={s.status} variant="outline" className="text-xs font-medium" data-testid={`chip-status-${s.status}`}>
                                {s.status}: {s.count} ({money(s.amount)})
                            </Badge>
                        ))}
                    </div>
                )}

                {/* Recent GMs table */}
                <div className="rounded-lg border overflow-hidden">
                    <Table>
                        <TableHeader className="bg-slate-100/50">
                            <TableRow>
                                <TableHead className="font-bold">Company</TableHead>
                                <TableHead className="font-bold">Type</TableHead>
                                <TableHead className="font-bold">Sales</TableHead>
                                <TableHead className="font-bold text-right">Amount</TableHead>
                                <TableHead className="font-bold">Status</TableHead>
                                <TableHead className="font-bold text-center">Invoices</TableHead>
                                <TableHead className="font-bold text-center">Payment</TableHead>
                                <TableHead className="font-bold text-center">Action</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {summaryQuery.isLoading && (
                                <TableRow><TableCell colSpan={8} className="text-center py-8 text-muted-foreground">Loading…</TableCell></TableRow>
                            )}
                            {!summaryQuery.isLoading && recentGms.length === 0 && (
                                <TableRow><TableCell colSpan={8} className="text-center py-8 text-muted-foreground">No GM entries match the filters.</TableCell></TableRow>
                            )}
                            {recentGms.map((gm) => (
                                <TableRow key={gm.id} data-testid={`row-gm-${gm.id}`}>
                                    <TableCell>
                                        <div className="font-medium">{gm.companyName || "—"}</div>
                                        <div className="text-[11px] text-muted-foreground">{gm.packageType}</div>
                                    </TableCell>
                                    <TableCell>
                                        <Badge variant="outline" className={`text-[10px] ${gmTypeBadge(gm.gmType)}`}>{gm.gmType}</Badge>
                                        {gm.loan?.overdue && <Badge variant="outline" className="ml-1 text-[10px] bg-rose-100 text-rose-700 border-rose-200">OVERDUE</Badge>}
                                    </TableCell>
                                    <TableCell className="text-sm">{gm.salesPersonName || "—"}</TableCell>
                                    <TableCell className="text-right text-sm">
                                        {money(gm.amountUsd)}
                                        {gm.gmType === "PARTIAL" && gm.partialPendingAmount != null && (
                                            <div className="text-[11px] text-amber-600">Due {money(gm.partialPendingAmount)}</div>
                                        )}
                                    </TableCell>
                                    <TableCell><Badge variant="outline" className="text-[10px]">{gm.status}</Badge></TableCell>
                                    <TableCell className="text-center text-sm">{gm.invoiceCount}</TableCell>
                                    <TableCell className="text-center">
                                        <Badge variant="outline" className={`text-[10px] ${paymentBadge(gm.paymentConfirmationStatus)}`}>{gm.paymentConfirmationStatus}</Badge>
                                    </TableCell>
                                    <TableCell className="text-center">
                                        <Button size="sm" variant="ghost" onClick={() => setDetailGmId(gm.id)} data-testid={`button-view-gm-${gm.id}`}>
                                            <Eye className="h-4 w-4" />
                                        </Button>
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </div>
            </CardContent>

            {/* GM detail dialog */}
            <Dialog open={!!detailGmId} onOpenChange={(open) => !open && setDetailGmId(null)}>
                <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
                    <DialogHeader>
                        <DialogTitle className="flex items-center gap-2">
                            <FileText className="h-5 w-5 text-emerald-600" />
                            GM Detail &amp; Linked Invoices
                        </DialogTitle>
                        <DialogDescription>
                            {detailQuery.data?.gm
                                ? `${detailQuery.data.gm.companyName} · ${detailQuery.data.gm.gmType} · ${detailQuery.data.gm.status}`
                                : "Loading GM details…"}
                        </DialogDescription>
                    </DialogHeader>

                    {detailQuery.isLoading && <div className="py-8 text-center text-muted-foreground">Loading…</div>}
                    {detailQuery.isError && <div className="py-8 text-center text-rose-600">Failed to load GM details.</div>}

                    {detailQuery.data && (
                        <div className="space-y-5">
                            {/* Header facts */}
                            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                                <div><span className="text-muted-foreground">Amount</span><div className="font-semibold">{money(detailQuery.data.gm.amountUsd)}</div></div>
                                <div><span className="text-muted-foreground">Customer $</span><div className="font-semibold">{detailQuery.data.gm.customerDollar ? money(detailQuery.data.gm.customerDollar) : "—"}</div></div>
                                <div><span className="text-muted-foreground">Sales</span><div className="font-semibold">{detailQuery.data.gm.salesPersonName || "—"}</div></div>
                                <div><span className="text-muted-foreground">Created</span><div className="font-semibold">{fmtDate(detailQuery.data.gm.createdAt)}</div></div>
                            </div>

                            {/* Loan terms */}
                            {detailQuery.data.loanTerms && (
                                <div className="rounded-lg border p-3 bg-violet-50/50 dark:bg-zinc-900">
                                    <h4 className="font-bold text-sm mb-2 flex items-center gap-1">
                                        <HandCoins className="h-4 w-4 text-violet-600" /> Loan Terms
                                        {detailQuery.data.loanTerms.overdue && <Badge variant="outline" className="text-[10px] bg-rose-100 text-rose-700 border-rose-200">OVERDUE</Badge>}
                                    </h4>
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                                        <div><span className="text-muted-foreground">Loan Amt</span><div className="font-semibold">{money(detailQuery.data.loanTerms.loanAmountUsd)}</div></div>
                                        <div><span className="text-muted-foreground">Return By</span><div className="font-semibold">{fmtDate(detailQuery.data.loanTerms.agreedReturnDate)}</div></div>
                                        <div><span className="text-muted-foreground">Admin</span><div className="font-semibold">{detailQuery.data.loanTerms.adminApprovalStatus || "—"}</div></div>
                                        <div><span className="text-muted-foreground">Return</span><div className="font-semibold">{detailQuery.data.loanTerms.returnStatus || "—"}</div></div>
                                    </div>
                                </div>
                            )}

                            {/* Partial receipts */}
                            {detailQuery.data.partialReceipts.length > 0 && (
                                <div>
                                    <h4 className="font-bold text-sm mb-2">
                                        Partial Receipts
                                        {detailQuery.data.summary.partialPendingTotal != null && (
                                            <span className="ml-2 text-xs font-normal text-amber-600">
                                                Received {money(detailQuery.data.summary.partialReceivedTotal)} · Pending {money(detailQuery.data.summary.partialPendingTotal)}
                                            </span>
                                        )}
                                    </h4>
                                    <div className="rounded-lg border overflow-hidden">
                                        <Table>
                                            <TableHeader className="bg-slate-100/50">
                                                <TableRow>
                                                    <TableHead>Date</TableHead>
                                                    <TableHead className="text-right">Amount</TableHead>
                                                    <TableHead>Method</TableHead>
                                                    <TableHead>Reference</TableHead>
                                                </TableRow>
                                            </TableHeader>
                                            <TableBody>
                                                {detailQuery.data.partialReceipts.map((r) => (
                                                    <TableRow key={r.id}>
                                                        <TableCell className="text-sm">{fmtDate(r.receiptDate)}</TableCell>
                                                        <TableCell className="text-right text-sm">{money(r.amountUsd)}</TableCell>
                                                        <TableCell className="text-sm">{r.method || "—"}</TableCell>
                                                        <TableCell className="text-sm">{r.reference || "—"}</TableCell>
                                                    </TableRow>
                                                ))}
                                            </TableBody>
                                        </Table>
                                    </div>
                                </div>
                            )}

                            {/* Invoices */}
                            <div>
                                <h4 className="font-bold text-sm mb-2">Linked Invoices ({detailQuery.data.summary.invoiceCount})</h4>
                                {detailQuery.data.invoices.length === 0 ? (
                                    <div className="text-sm text-muted-foreground py-4 text-center border rounded-lg">No invoices linked to this GM.</div>
                                ) : (
                                    <div className="rounded-lg border overflow-hidden">
                                        <Table>
                                            <TableHeader className="bg-slate-100/50">
                                                <TableRow>
                                                    <TableHead>Type</TableHead>
                                                    <TableHead className="text-right">Amount</TableHead>
                                                    <TableHead>Status</TableHead>
                                                    <TableHead>HOD</TableHead>
                                                    <TableHead>Accounts</TableHead>
                                                    <TableHead>Project</TableHead>
                                                </TableRow>
                                            </TableHeader>
                                            <TableBody>
                                                {detailQuery.data.invoices.map((inv) => (
                                                    <TableRow key={inv.id}>
                                                        <TableCell className="text-sm">
                                                            {inv.invoiceType || "—"}
                                                            <div className="text-[10px] text-muted-foreground">{inv.autoGenerated ? "auto" : "manual"}</div>
                                                        </TableCell>
                                                        <TableCell className="text-right text-sm">{money(inv.amount)}</TableCell>
                                                        <TableCell><Badge variant="outline" className="text-[10px]">{inv.status}</Badge></TableCell>
                                                        <TableCell className="text-[11px]">{inv.hodApprovedAt ? `✓ ${fmtDate(inv.hodApprovedAt)}` : "—"}</TableCell>
                                                        <TableCell className="text-[11px]">{inv.accountsApprovedAt ? `✓ ${fmtDate(inv.accountsApprovedAt)}` : "—"}</TableCell>
                                                        <TableCell className="text-[11px]">
                                                            {inv.projects.length > 0
                                                                ? inv.projects.map((p) => `${p.name} (${p.status})`).join(", ")
                                                                : inv.projectName || "—"}
                                                        </TableCell>
                                                    </TableRow>
                                                ))}
                                            </TableBody>
                                        </Table>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </DialogContent>
            </Dialog>
        </Card>
    );
}
